version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    depends_on:
      - mongodb 
    environment:
      MONGO_DB_HOST: "mongodb"
    networks:
      - gomongo  

  mongodb:     
    image: mongo
  
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gomongo 

networks:
  gomongo:
    driver: bridge      

volumes:
  mongodb_data:
